export type ProductStatus = "draft" | "active" | "inactive";
export type MasterStatus = "active" | "inactive";
export type Master = {
    id: number;
    code: string;
    name: string;
    description?: string | null;
    status: MasterStatus;
    parent_id?: number | null;
    sort_order?: number;
    symbol?: string;
    decimal_precision?: number;
};
export type RetailPrice = {
    unit_price: string;
    currency: string;
    pricing_context: "retail";
    price_list_id?: number;
    price_list_item_id?: number;
};
export type ProductVariant = {
    id: number;
    product_id: number;
    sku: string;
    variant_name: string;
    unit_id: number;
    unit?: Master;
    unit_symbol?: string;
    status: MasterStatus;
    sellable_retail: boolean;
    sellable_dealer: boolean;
    clinic_material: boolean;
    track_inventory?: boolean;
    track_batch?: boolean;
    track_expiry?: boolean;
    specifications?: Record<string, string> | null;
    retail_price?: RetailPrice;
};
export type ProductImage = {
    id: number;
    path?: string;
    url?: string;
    alt_text: string | null;
    product_variant_id: number | null;
    is_primary: boolean;
    sort_order?: number;
};
export type Product = {
    id: number;
    product_code: string;
    name: string;
    slug: string;
    description: string | null;
    product_category_id: number;
    brand_id: number | null;
    category: Master | null;
    brand: Master | null;
    status: ProductStatus;
    track_inventory?: boolean;
    track_batch?: boolean;
    track_expiry?: boolean;
    default_low_stock_threshold?: string | null;
    variants: ProductVariant[];
    images: ProductImage[];
    retail_price?: RetailPrice;
    wizard_key?: string | null;
    wizard_data?: Record<string, unknown> | null;
    youtube_videos?: string[] | null;
    usage_instructions?: string | null;
    images_count?: number;
};
export type PriceListItem = {
    id: number;
    product_variant_id: number;
    variant?: ProductVariant;
    unit_price: string;
    minimum_quantity: string;
    status: MasterStatus;
    effective_from: string | null;
    effective_to: string | null;
};
export type PriceList = {
    id: number;
    code: string;
    name: string;
    pricing_context: "retail";
    scope_type: "all";
    currency: "VND";
    priority: number;
    status: MasterStatus;
    effective_from: string | null;
    effective_to: string | null;
    items?: PriceListItem[];
    items_count?: number;
};
export type RawPage<T> = { data: T[]; current_page: number; last_page: number; total: number };
