export type ProductStatus = "draft" | "active" | "inactive";
export type MasterStatus = "active" | "inactive";
export type Master = {
    id: number;
    code: string;
    name: string;
    description?: string | null;
    status: MasterStatus;
    parent_id?: number | null;
    sort_order?: number;
    symbol?: string;
    decimal_precision?: number;
};
export type RetailPrice = {
    unit_price: string;
    discounted_unit_price?: string | null;
    currency: string;
    pricing_context: "retail";
    price_list_id?: number;
    price_list_item_id?: number;
};
export type GiftPromotionSummary = {
    code: string;
    name: string;
    buy_variant_id: number | null;
    buy_variant_name?: string | null;
    minimum_buy_quantity: string;
    minimum_order_amount?: string;
    gift_product_name: string;
    gift_image_url?: string | null;
    gift_variant_name: string;
    gift_sku: string;
    gift_quantity: string;
    repeat_per_multiple: boolean;
    gift_available: boolean;
};
export type RetailPromotionSummary = {
    id?: number;
    code: string;
    discount_type: "percentage" | "fixed_amount";
    discount_value: string;
    max_discount_amount: string | null;
    minimum_order_amount: string;
    total_usage_limit: number | null;
    per_buyer_usage_limit: number | null;
};
export type ProductVariant = {
    id: number;
    product_id: number;
    sku: string;
    variant_name: string;
    unit_id: number;
    unit?: Master;
    unit_symbol?: string;
    unit_precision?: number;
    status: MasterStatus;
    sellable_retail: boolean;
    sellable_dealer: boolean;
    clinic_material: boolean;
    track_inventory?: boolean;
    track_batch?: boolean;
    track_expiry?: boolean;
    specifications?: Record<string, string> | null;
    retail_price?: RetailPrice;
};
export type ProductImage = {
    id: number;
    path?: string;
    url?: string;
    alt_text: string | null;
    product_variant_id: number | null;
    is_primary: boolean;
    sort_order?: number;
};
export type Product = {
    id: number;
    product_code: string;
    base_sku?: string | null;
    name: string;
    slug: string;
    description: string | null;
    product_category_id: number;
    brand_id: number | null;
    category: Master | null;
    brand: Master | null;
    status: ProductStatus;
    track_inventory?: boolean;
    can_be_gift?: boolean;
    gift_only?: boolean;
    gift_promotions?: GiftPromotionSummary[];
    retail_promotions?: RetailPromotionSummary[];
    retail_discount_promotion?: RetailPromotionSummary | null;
    active_discount_promotion?: {
        id: number;
        name: string;
        discount_type: "percentage" | "fixed_amount";
        discount_value: string;
    } | null;
    track_batch?: boolean;
    track_expiry?: boolean;
    default_low_stock_threshold?: string | null;
    variants: ProductVariant[];
    images: ProductImage[];
    retail_price?: RetailPrice;
    wizard_key?: string | null;
    wizard_data?: Record<string, unknown> | null;
    youtube_videos?: string[] | null;
    usage_instructions?: string | null;
    images_count?: number;
};
export type PriceListItem = {
    id: number;
    product_variant_id: number;
    variant?: ProductVariant;
    unit_price: string;
    minimum_quantity: string;
    status: MasterStatus;
    effective_from: string | null;
    effective_to: string | null;
};
export type PriceList = {
    id: number;
    code: string;
    name: string;
    pricing_context: "retail";
    scope_type: "all";
    currency: "VND";
    priority: number;
    status: MasterStatus;
    effective_from: string | null;
    effective_to: string | null;
    items?: PriceListItem[];
    items_count?: number;
};
export type RawPage<T> = { data: T[]; current_page: number; last_page: number; total: number };
