/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppointmentLookupRouteImport } from './routes/appointment-lookup'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ReceptionistRouteImport } from './routes/receptionist'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SetupPasswordRouteImport } from './routes/setup-password'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountAppointmentsRouteImport } from './routes/account.appointments'
import { Route as AccountHistoryRouteImport } from './routes/account.history'
import { Route as AccountLoyaltyRouteImport } from './routes/account.loyalty'
import { Route as AccountNotificationsRouteImport } from './routes/account.notifications'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountVouchersRouteImport } from './routes/account.vouchers'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAppointmentsRouteImport } from './routes/admin.appointments'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminBlogCategoriesRouteImport } from './routes/admin.blog-categories'
import { Route as AdminBlogsRouteImport } from './routes/admin.blogs'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminDoctorsRouteImport } from './routes/admin.doctors'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminServiceCategoriesRouteImport } from './routes/admin.service-categories'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminVoucherManagementRouteImport } from './routes/admin.voucher-management'
import { Route as AdminVouchersRouteImport } from './routes/admin.vouchers'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'
import { Route as BookingSuccessRouteImport } from './routes/booking.success'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as DoctorAppointmentsRouteImport } from './routes/doctor.appointments'
import { Route as DoctorNotificationsRouteImport } from './routes/doctor.notifications'
import { Route as DoctorReviewsRouteImport } from './routes/doctor.reviews'
import { Route as DoctorScheduleRouteImport } from './routes/doctor.schedule'
import { Route as DoctorTodayRouteImport } from './routes/doctor.today'
import { Route as DoctorsSlugRouteImport } from './routes/doctors.$slug'
import { Route as ReceptionistIndexRouteImport } from './routes/receptionist.index'
import { Route as ReceptionistAppointmentsRouteImport } from './routes/receptionist.appointments'
import { Route as ReceptionistCustomersRouteImport } from './routes/receptionist.customers'
import { Route as ReceptionistNotificationsRouteImport } from './routes/receptionist.notifications'
import { Route as ReceptionistTodayRouteImport } from './routes/receptionist.today'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesCategorySlugRouteImport } from './routes/services.$categorySlug'
import { Route as AccountAppointmentsIndexRouteImport } from './routes/account.appointments.index'
import { Route as AccountAppointmentsIdRouteImport } from './routes/account.appointments.$id'
import { Route as AdminAppointmentsIndexRouteImport } from './routes/admin.appointments.index'
import { Route as AdminAppointmentsIdRouteImport } from './routes/admin.appointments.$id'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin.customers.index'
import { Route as AdminCustomersIdRouteImport } from './routes/admin.customers.$id'
import { Route as AdminDoctorsIndexRouteImport } from './routes/admin.doctors.index'
import { Route as AdminDoctorsIdRouteImport } from './routes/admin.doctors.$id'
import { Route as AdminServicesIdRouteImport } from './routes/admin.services.$id'
import { Route as DoctorAppointmentsIndexRouteImport } from './routes/doctor.appointments.index'
import { Route as DoctorAppointmentsIdRouteImport } from './routes/doctor.appointments.$id'
import { Route as ReceptionistAppointmentsIndexRouteImport } from './routes/receptionist.appointments.index'
import { Route as ReceptionistAppointmentsIdRouteImport } from './routes/receptionist.appointments.$id'
import { Route as ServicesCategorySlugIndexRouteImport } from './routes/services.$categorySlug.index'
import { Route as ServicesCategorySlugServiceSlugRouteImport } from './routes/services.$categorySlug.$serviceSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentLookupRoute = AppointmentLookupRouteImport.update({
  id: '/appointment-lookup',
  path: '/appointment-lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionistRoute = ReceptionistRouteImport.update({
  id: '/receptionist',
  path: '/receptionist',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupPasswordRoute = SetupPasswordRouteImport.update({
  id: '/setup-password',
  path: '/setup-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAppointmentsRoute = AccountAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AccountRoute,
} as any)
const AccountHistoryRoute = AccountHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AccountRoute,
} as any)
const AccountLoyaltyRoute = AccountLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => AccountRoute,
} as any)
const AccountNotificationsRoute = AccountNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountVouchersRoute = AccountVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => AccountRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogCategoriesRoute = AdminBlogCategoriesRouteImport.update({
  id: '/blog-categories',
  path: '/blog-categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsRoute = AdminBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDoctorsRoute = AdminDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServiceCategoriesRoute = AdminServiceCategoriesRouteImport.update({
  id: '/service-categories',
  path: '/service-categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVoucherManagementRoute = AdminVoucherManagementRouteImport.update({
  id: '/voucher-management',
  path: '/voucher-management',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVouchersRoute = AdminVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => AdminRoute,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogsRoute,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogsRoute,
} as any)
const BookingSuccessRoute = BookingSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => BookingRoute,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorAppointmentsRoute = DoctorAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorNotificationsRoute = DoctorNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorReviewsRoute = DoctorReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorScheduleRoute = DoctorScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorTodayRoute = DoctorTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorsSlugRoute = DoctorsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DoctorsRoute,
} as any)
const ReceptionistIndexRoute = ReceptionistIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReceptionistRoute,
} as any)
const ReceptionistAppointmentsRoute =
  ReceptionistAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => ReceptionistRoute,
  } as any)
const ReceptionistCustomersRoute = ReceptionistCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => ReceptionistRoute,
} as any)
const ReceptionistNotificationsRoute =
  ReceptionistNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => ReceptionistRoute,
  } as any)
const ReceptionistTodayRoute = ReceptionistTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => ReceptionistRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCategorySlugRoute = ServicesCategorySlugRouteImport.update({
  id: '/$categorySlug',
  path: '/$categorySlug',
  getParentRoute: () => ServicesRoute,
} as any)
const AccountAppointmentsIndexRoute =
  AccountAppointmentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AccountAppointmentsRoute,
  } as any)
const AccountAppointmentsIdRoute = AccountAppointmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AccountAppointmentsRoute,
} as any)
const AdminAppointmentsIndexRoute = AdminAppointmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAppointmentsRoute,
} as any)
const AdminAppointmentsIdRoute = AdminAppointmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAppointmentsRoute,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCustomersRoute,
} as any)
const AdminCustomersIdRoute = AdminCustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCustomersRoute,
} as any)
const AdminDoctorsIndexRoute = AdminDoctorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDoctorsRoute,
} as any)
const AdminDoctorsIdRoute = AdminDoctorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminDoctorsRoute,
} as any)
const AdminServicesIdRoute = AdminServicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminServicesRoute,
} as any)
const DoctorAppointmentsIndexRoute = DoctorAppointmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorAppointmentsRoute,
} as any)
const DoctorAppointmentsIdRoute = DoctorAppointmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DoctorAppointmentsRoute,
} as any)
const ReceptionistAppointmentsIndexRoute =
  ReceptionistAppointmentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ReceptionistAppointmentsRoute,
  } as any)
const ReceptionistAppointmentsIdRoute =
  ReceptionistAppointmentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ReceptionistAppointmentsRoute,
  } as any)
const ServicesCategorySlugIndexRoute =
  ServicesCategorySlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ServicesCategorySlugRoute,
  } as any)
const ServicesCategorySlugServiceSlugRoute =
  ServicesCategorySlugServiceSlugRouteImport.update({
    id: '/$serviceSlug',
    path: '/$serviceSlug',
    getParentRoute: () => ServicesCategorySlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/appointment-lookup': typeof AppointmentLookupRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/booking': typeof BookingRouteWithChildren
  '/doctor': typeof DoctorRouteWithChildren
  '/doctors': typeof DoctorsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/receptionist': typeof ReceptionistRouteWithChildren
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRouteWithChildren
  '/setup-password': typeof SetupPasswordRoute
  '/account/appointments': typeof AccountAppointmentsRouteWithChildren
  '/account/history': typeof AccountHistoryRoute
  '/account/loyalty': typeof AccountLoyaltyRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/vouchers': typeof AccountVouchersRoute
  '/admin/appointments': typeof AdminAppointmentsRouteWithChildren
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/blog-categories': typeof AdminBlogCategoriesRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/doctors': typeof AdminDoctorsRouteWithChildren
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/service-categories': typeof AdminServiceCategoriesRoute
  '/admin/services': typeof AdminServicesRouteWithChildren
  '/admin/staff': typeof AdminStaffRoute
  '/admin/voucher-management': typeof AdminVoucherManagementRoute
  '/admin/vouchers': typeof AdminVouchersRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/booking/success': typeof BookingSuccessRoute
  '/doctor/appointments': typeof DoctorAppointmentsRouteWithChildren
  '/doctor/notifications': typeof DoctorNotificationsRoute
  '/doctor/reviews': typeof DoctorReviewsRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/doctor/today': typeof DoctorTodayRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/receptionist/appointments': typeof ReceptionistAppointmentsRouteWithChildren
  '/receptionist/customers': typeof ReceptionistCustomersRoute
  '/receptionist/notifications': typeof ReceptionistNotificationsRoute
  '/receptionist/today': typeof ReceptionistTodayRoute
  '/services/$categorySlug': typeof ServicesCategorySlugRouteWithChildren
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/receptionist/': typeof ReceptionistIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/account/appointments/$id': typeof AccountAppointmentsIdRoute
  '/admin/appointments/$id': typeof AdminAppointmentsIdRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/doctors/$id': typeof AdminDoctorsIdRoute
  '/admin/services/$id': typeof AdminServicesIdRoute
  '/doctor/appointments/$id': typeof DoctorAppointmentsIdRoute
  '/receptionist/appointments/$id': typeof ReceptionistAppointmentsIdRoute
  '/services/$categorySlug/$serviceSlug': typeof ServicesCategorySlugServiceSlugRoute
  '/account/appointments/': typeof AccountAppointmentsIndexRoute
  '/admin/appointments/': typeof AdminAppointmentsIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/doctors/': typeof AdminDoctorsIndexRoute
  '/doctor/appointments/': typeof DoctorAppointmentsIndexRoute
  '/receptionist/appointments/': typeof ReceptionistAppointmentsIndexRoute
  '/services/$categorySlug/': typeof ServicesCategorySlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointment-lookup': typeof AppointmentLookupRoute
  '/booking': typeof BookingRouteWithChildren
  '/doctors': typeof DoctorsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/setup-password': typeof SetupPasswordRoute
  '/account/history': typeof AccountHistoryRoute
  '/account/loyalty': typeof AccountLoyaltyRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/vouchers': typeof AccountVouchersRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/blog-categories': typeof AdminBlogCategoriesRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/service-categories': typeof AdminServiceCategoriesRoute
  '/admin/services': typeof AdminServicesRouteWithChildren
  '/admin/staff': typeof AdminStaffRoute
  '/admin/voucher-management': typeof AdminVoucherManagementRoute
  '/admin/vouchers': typeof AdminVouchersRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/booking/success': typeof BookingSuccessRoute
  '/doctor/notifications': typeof DoctorNotificationsRoute
  '/doctor/reviews': typeof DoctorReviewsRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/doctor/today': typeof DoctorTodayRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/receptionist/customers': typeof ReceptionistCustomersRoute
  '/receptionist/notifications': typeof ReceptionistNotificationsRoute
  '/receptionist/today': typeof ReceptionistTodayRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/blogs': typeof BlogsIndexRoute
  '/doctor': typeof DoctorIndexRoute
  '/receptionist': typeof ReceptionistIndexRoute
  '/services': typeof ServicesIndexRoute
  '/account/appointments/$id': typeof AccountAppointmentsIdRoute
  '/admin/appointments/$id': typeof AdminAppointmentsIdRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/doctors/$id': typeof AdminDoctorsIdRoute
  '/admin/services/$id': typeof AdminServicesIdRoute
  '/doctor/appointments/$id': typeof DoctorAppointmentsIdRoute
  '/receptionist/appointments/$id': typeof ReceptionistAppointmentsIdRoute
  '/services/$categorySlug/$serviceSlug': typeof ServicesCategorySlugServiceSlugRoute
  '/account/appointments': typeof AccountAppointmentsIndexRoute
  '/admin/appointments': typeof AdminAppointmentsIndexRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/doctors': typeof AdminDoctorsIndexRoute
  '/doctor/appointments': typeof DoctorAppointmentsIndexRoute
  '/receptionist/appointments': typeof ReceptionistAppointmentsIndexRoute
  '/services/$categorySlug': typeof ServicesCategorySlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/appointment-lookup': typeof AppointmentLookupRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/booking': typeof BookingRouteWithChildren
  '/doctor': typeof DoctorRouteWithChildren
  '/doctors': typeof DoctorsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/receptionist': typeof ReceptionistRouteWithChildren
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRouteWithChildren
  '/setup-password': typeof SetupPasswordRoute
  '/account/appointments': typeof AccountAppointmentsRouteWithChildren
  '/account/history': typeof AccountHistoryRoute
  '/account/loyalty': typeof AccountLoyaltyRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/vouchers': typeof AccountVouchersRoute
  '/admin/appointments': typeof AdminAppointmentsRouteWithChildren
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/blog-categories': typeof AdminBlogCategoriesRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/doctors': typeof AdminDoctorsRouteWithChildren
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/service-categories': typeof AdminServiceCategoriesRoute
  '/admin/services': typeof AdminServicesRouteWithChildren
  '/admin/staff': typeof AdminStaffRoute
  '/admin/voucher-management': typeof AdminVoucherManagementRoute
  '/admin/vouchers': typeof AdminVouchersRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/booking/success': typeof BookingSuccessRoute
  '/doctor/appointments': typeof DoctorAppointmentsRouteWithChildren
  '/doctor/notifications': typeof DoctorNotificationsRoute
  '/doctor/reviews': typeof DoctorReviewsRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/doctor/today': typeof DoctorTodayRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/receptionist/appointments': typeof ReceptionistAppointmentsRouteWithChildren
  '/receptionist/customers': typeof ReceptionistCustomersRoute
  '/receptionist/notifications': typeof ReceptionistNotificationsRoute
  '/receptionist/today': typeof ReceptionistTodayRoute
  '/services/$categorySlug': typeof ServicesCategorySlugRouteWithChildren
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/receptionist/': typeof ReceptionistIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/account/appointments/$id': typeof AccountAppointmentsIdRoute
  '/admin/appointments/$id': typeof AdminAppointmentsIdRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/doctors/$id': typeof AdminDoctorsIdRoute
  '/admin/services/$id': typeof AdminServicesIdRoute
  '/doctor/appointments/$id': typeof DoctorAppointmentsIdRoute
  '/receptionist/appointments/$id': typeof ReceptionistAppointmentsIdRoute
  '/services/$categorySlug/$serviceSlug': typeof ServicesCategorySlugServiceSlugRoute
  '/account/appointments/': typeof AccountAppointmentsIndexRoute
  '/admin/appointments/': typeof AdminAppointmentsIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/doctors/': typeof AdminDoctorsIndexRoute
  '/doctor/appointments/': typeof DoctorAppointmentsIndexRoute
  '/receptionist/appointments/': typeof ReceptionistAppointmentsIndexRoute
  '/services/$categorySlug/': typeof ServicesCategorySlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/appointment-lookup'
    | '/blogs'
    | '/booking'
    | '/doctor'
    | '/doctors'
    | '/forgot-password'
    | '/login'
    | '/receptionist'
    | '/register'
    | '/services'
    | '/setup-password'
    | '/account/appointments'
    | '/account/history'
    | '/account/loyalty'
    | '/account/notifications'
    | '/account/profile'
    | '/account/vouchers'
    | '/admin/appointments'
    | '/admin/audit-logs'
    | '/admin/blog-categories'
    | '/admin/blogs'
    | '/admin/customers'
    | '/admin/doctors'
    | '/admin/notifications'
    | '/admin/reviews'
    | '/admin/service-categories'
    | '/admin/services'
    | '/admin/staff'
    | '/admin/voucher-management'
    | '/admin/vouchers'
    | '/blogs/$slug'
    | '/booking/success'
    | '/doctor/appointments'
    | '/doctor/notifications'
    | '/doctor/reviews'
    | '/doctor/schedule'
    | '/doctor/today'
    | '/doctors/$slug'
    | '/receptionist/appointments'
    | '/receptionist/customers'
    | '/receptionist/notifications'
    | '/receptionist/today'
    | '/services/$categorySlug'
    | '/account/'
    | '/admin/'
    | '/blogs/'
    | '/doctor/'
    | '/receptionist/'
    | '/services/'
    | '/account/appointments/$id'
    | '/admin/appointments/$id'
    | '/admin/customers/$id'
    | '/admin/doctors/$id'
    | '/admin/services/$id'
    | '/doctor/appointments/$id'
    | '/receptionist/appointments/$id'
    | '/services/$categorySlug/$serviceSlug'
    | '/account/appointments/'
    | '/admin/appointments/'
    | '/admin/customers/'
    | '/admin/doctors/'
    | '/doctor/appointments/'
    | '/receptionist/appointments/'
    | '/services/$categorySlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointment-lookup'
    | '/booking'
    | '/doctors'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/setup-password'
    | '/account/history'
    | '/account/loyalty'
    | '/account/notifications'
    | '/account/profile'
    | '/account/vouchers'
    | '/admin/audit-logs'
    | '/admin/blog-categories'
    | '/admin/blogs'
    | '/admin/notifications'
    | '/admin/reviews'
    | '/admin/service-categories'
    | '/admin/services'
    | '/admin/staff'
    | '/admin/voucher-management'
    | '/admin/vouchers'
    | '/blogs/$slug'
    | '/booking/success'
    | '/doctor/notifications'
    | '/doctor/reviews'
    | '/doctor/schedule'
    | '/doctor/today'
    | '/doctors/$slug'
    | '/receptionist/customers'
    | '/receptionist/notifications'
    | '/receptionist/today'
    | '/account'
    | '/admin'
    | '/blogs'
    | '/doctor'
    | '/receptionist'
    | '/services'
    | '/account/appointments/$id'
    | '/admin/appointments/$id'
    | '/admin/customers/$id'
    | '/admin/doctors/$id'
    | '/admin/services/$id'
    | '/doctor/appointments/$id'
    | '/receptionist/appointments/$id'
    | '/services/$categorySlug/$serviceSlug'
    | '/account/appointments'
    | '/admin/appointments'
    | '/admin/customers'
    | '/admin/doctors'
    | '/doctor/appointments'
    | '/receptionist/appointments'
    | '/services/$categorySlug'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/appointment-lookup'
    | '/blogs'
    | '/booking'
    | '/doctor'
    | '/doctors'
    | '/forgot-password'
    | '/login'
    | '/receptionist'
    | '/register'
    | '/services'
    | '/setup-password'
    | '/account/appointments'
    | '/account/history'
    | '/account/loyalty'
    | '/account/notifications'
    | '/account/profile'
    | '/account/vouchers'
    | '/admin/appointments'
    | '/admin/audit-logs'
    | '/admin/blog-categories'
    | '/admin/blogs'
    | '/admin/customers'
    | '/admin/doctors'
    | '/admin/notifications'
    | '/admin/reviews'
    | '/admin/service-categories'
    | '/admin/services'
    | '/admin/staff'
    | '/admin/voucher-management'
    | '/admin/vouchers'
    | '/blogs/$slug'
    | '/booking/success'
    | '/doctor/appointments'
    | '/doctor/notifications'
    | '/doctor/reviews'
    | '/doctor/schedule'
    | '/doctor/today'
    | '/doctors/$slug'
    | '/receptionist/appointments'
    | '/receptionist/customers'
    | '/receptionist/notifications'
    | '/receptionist/today'
    | '/services/$categorySlug'
    | '/account/'
    | '/admin/'
    | '/blogs/'
    | '/doctor/'
    | '/receptionist/'
    | '/services/'
    | '/account/appointments/$id'
    | '/admin/appointments/$id'
    | '/admin/customers/$id'
    | '/admin/doctors/$id'
    | '/admin/services/$id'
    | '/doctor/appointments/$id'
    | '/receptionist/appointments/$id'
    | '/services/$categorySlug/$serviceSlug'
    | '/account/appointments/'
    | '/admin/appointments/'
    | '/admin/customers/'
    | '/admin/doctors/'
    | '/doctor/appointments/'
    | '/receptionist/appointments/'
    | '/services/$categorySlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AppointmentLookupRoute: typeof AppointmentLookupRoute
  BlogsRoute: typeof BlogsRouteWithChildren
  BookingRoute: typeof BookingRouteWithChildren
  DoctorRoute: typeof DoctorRouteWithChildren
  DoctorsRoute: typeof DoctorsRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ReceptionistRoute: typeof ReceptionistRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SetupPasswordRoute: typeof SetupPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointment-lookup': {
      id: '/appointment-lookup'
      path: '/appointment-lookup'
      fullPath: '/appointment-lookup'
      preLoaderRoute: typeof AppointmentLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receptionist': {
      id: '/receptionist'
      path: '/receptionist'
      fullPath: '/receptionist'
      preLoaderRoute: typeof ReceptionistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-password': {
      id: '/setup-password'
      path: '/setup-password'
      fullPath: '/setup-password'
      preLoaderRoute: typeof SetupPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/appointments': {
      id: '/account/appointments'
      path: '/appointments'
      fullPath: '/account/appointments'
      preLoaderRoute: typeof AccountAppointmentsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/history': {
      id: '/account/history'
      path: '/history'
      fullPath: '/account/history'
      preLoaderRoute: typeof AccountHistoryRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/loyalty': {
      id: '/account/loyalty'
      path: '/loyalty'
      fullPath: '/account/loyalty'
      preLoaderRoute: typeof AccountLoyaltyRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/notifications': {
      id: '/account/notifications'
      path: '/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AccountNotificationsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/vouchers': {
      id: '/account/vouchers'
      path: '/vouchers'
      fullPath: '/account/vouchers'
      preLoaderRoute: typeof AccountVouchersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog-categories': {
      id: '/admin/blog-categories'
      path: '/blog-categories'
      fullPath: '/admin/blog-categories'
      preLoaderRoute: typeof AdminBlogCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs': {
      id: '/admin/blogs'
      path: '/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/doctors': {
      id: '/admin/doctors'
      path: '/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AdminDoctorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/service-categories': {
      id: '/admin/service-categories'
      path: '/service-categories'
      fullPath: '/admin/service-categories'
      preLoaderRoute: typeof AdminServiceCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/voucher-management': {
      id: '/admin/voucher-management'
      path: '/voucher-management'
      fullPath: '/admin/voucher-management'
      preLoaderRoute: typeof AdminVoucherManagementRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vouchers': {
      id: '/admin/vouchers'
      path: '/vouchers'
      fullPath: '/admin/vouchers'
      preLoaderRoute: typeof AdminVouchersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/booking/success': {
      id: '/booking/success'
      path: '/success'
      fullPath: '/booking/success'
      preLoaderRoute: typeof BookingSuccessRouteImport
      parentRoute: typeof BookingRoute
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/appointments': {
      id: '/doctor/appointments'
      path: '/appointments'
      fullPath: '/doctor/appointments'
      preLoaderRoute: typeof DoctorAppointmentsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/notifications': {
      id: '/doctor/notifications'
      path: '/notifications'
      fullPath: '/doctor/notifications'
      preLoaderRoute: typeof DoctorNotificationsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/reviews': {
      id: '/doctor/reviews'
      path: '/reviews'
      fullPath: '/doctor/reviews'
      preLoaderRoute: typeof DoctorReviewsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/schedule': {
      id: '/doctor/schedule'
      path: '/schedule'
      fullPath: '/doctor/schedule'
      preLoaderRoute: typeof DoctorScheduleRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/today': {
      id: '/doctor/today'
      path: '/today'
      fullPath: '/doctor/today'
      preLoaderRoute: typeof DoctorTodayRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctors/$slug': {
      id: '/doctors/$slug'
      path: '/$slug'
      fullPath: '/doctors/$slug'
      preLoaderRoute: typeof DoctorsSlugRouteImport
      parentRoute: typeof DoctorsRoute
    }
    '/receptionist/': {
      id: '/receptionist/'
      path: '/'
      fullPath: '/receptionist/'
      preLoaderRoute: typeof ReceptionistIndexRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/receptionist/appointments': {
      id: '/receptionist/appointments'
      path: '/appointments'
      fullPath: '/receptionist/appointments'
      preLoaderRoute: typeof ReceptionistAppointmentsRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/receptionist/customers': {
      id: '/receptionist/customers'
      path: '/customers'
      fullPath: '/receptionist/customers'
      preLoaderRoute: typeof ReceptionistCustomersRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/receptionist/notifications': {
      id: '/receptionist/notifications'
      path: '/notifications'
      fullPath: '/receptionist/notifications'
      preLoaderRoute: typeof ReceptionistNotificationsRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/receptionist/today': {
      id: '/receptionist/today'
      path: '/today'
      fullPath: '/receptionist/today'
      preLoaderRoute: typeof ReceptionistTodayRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$categorySlug': {
      id: '/services/$categorySlug'
      path: '/$categorySlug'
      fullPath: '/services/$categorySlug'
      preLoaderRoute: typeof ServicesCategorySlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/account/appointments/': {
      id: '/account/appointments/'
      path: '/'
      fullPath: '/account/appointments/'
      preLoaderRoute: typeof AccountAppointmentsIndexRouteImport
      parentRoute: typeof AccountAppointmentsRoute
    }
    '/account/appointments/$id': {
      id: '/account/appointments/$id'
      path: '/$id'
      fullPath: '/account/appointments/$id'
      preLoaderRoute: typeof AccountAppointmentsIdRouteImport
      parentRoute: typeof AccountAppointmentsRoute
    }
    '/admin/appointments/': {
      id: '/admin/appointments/'
      path: '/'
      fullPath: '/admin/appointments/'
      preLoaderRoute: typeof AdminAppointmentsIndexRouteImport
      parentRoute: typeof AdminAppointmentsRoute
    }
    '/admin/appointments/$id': {
      id: '/admin/appointments/$id'
      path: '/$id'
      fullPath: '/admin/appointments/$id'
      preLoaderRoute: typeof AdminAppointmentsIdRouteImport
      parentRoute: typeof AdminAppointmentsRoute
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/customers/$id': {
      id: '/admin/customers/$id'
      path: '/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AdminCustomersIdRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/doctors/': {
      id: '/admin/doctors/'
      path: '/'
      fullPath: '/admin/doctors/'
      preLoaderRoute: typeof AdminDoctorsIndexRouteImport
      parentRoute: typeof AdminDoctorsRoute
    }
    '/admin/doctors/$id': {
      id: '/admin/doctors/$id'
      path: '/$id'
      fullPath: '/admin/doctors/$id'
      preLoaderRoute: typeof AdminDoctorsIdRouteImport
      parentRoute: typeof AdminDoctorsRoute
    }
    '/admin/services/$id': {
      id: '/admin/services/$id'
      path: '/$id'
      fullPath: '/admin/services/$id'
      preLoaderRoute: typeof AdminServicesIdRouteImport
      parentRoute: typeof AdminServicesRoute
    }
    '/doctor/appointments/': {
      id: '/doctor/appointments/'
      path: '/'
      fullPath: '/doctor/appointments/'
      preLoaderRoute: typeof DoctorAppointmentsIndexRouteImport
      parentRoute: typeof DoctorAppointmentsRoute
    }
    '/doctor/appointments/$id': {
      id: '/doctor/appointments/$id'
      path: '/$id'
      fullPath: '/doctor/appointments/$id'
      preLoaderRoute: typeof DoctorAppointmentsIdRouteImport
      parentRoute: typeof DoctorAppointmentsRoute
    }
    '/receptionist/appointments/': {
      id: '/receptionist/appointments/'
      path: '/'
      fullPath: '/receptionist/appointments/'
      preLoaderRoute: typeof ReceptionistAppointmentsIndexRouteImport
      parentRoute: typeof ReceptionistAppointmentsRoute
    }
    '/receptionist/appointments/$id': {
      id: '/receptionist/appointments/$id'
      path: '/$id'
      fullPath: '/receptionist/appointments/$id'
      preLoaderRoute: typeof ReceptionistAppointmentsIdRouteImport
      parentRoute: typeof ReceptionistAppointmentsRoute
    }
    '/services/$categorySlug/': {
      id: '/services/$categorySlug/'
      path: '/'
      fullPath: '/services/$categorySlug/'
      preLoaderRoute: typeof ServicesCategorySlugIndexRouteImport
      parentRoute: typeof ServicesCategorySlugRoute
    }
    '/services/$categorySlug/$serviceSlug': {
      id: '/services/$categorySlug/$serviceSlug'
      path: '/$serviceSlug'
      fullPath: '/services/$categorySlug/$serviceSlug'
      preLoaderRoute: typeof ServicesCategorySlugServiceSlugRouteImport
      parentRoute: typeof ServicesCategorySlugRoute
    }
  }
}

interface AccountAppointmentsRouteChildren {
  AccountAppointmentsIdRoute: typeof AccountAppointmentsIdRoute
  AccountAppointmentsIndexRoute: typeof AccountAppointmentsIndexRoute
}

const AccountAppointmentsRouteChildren: AccountAppointmentsRouteChildren = {
  AccountAppointmentsIdRoute: AccountAppointmentsIdRoute,
  AccountAppointmentsIndexRoute: AccountAppointmentsIndexRoute,
}

const AccountAppointmentsRouteWithChildren =
  AccountAppointmentsRoute._addFileChildren(AccountAppointmentsRouteChildren)

interface AccountRouteChildren {
  AccountAppointmentsRoute: typeof AccountAppointmentsRouteWithChildren
  AccountHistoryRoute: typeof AccountHistoryRoute
  AccountLoyaltyRoute: typeof AccountLoyaltyRoute
  AccountNotificationsRoute: typeof AccountNotificationsRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountVouchersRoute: typeof AccountVouchersRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAppointmentsRoute: AccountAppointmentsRouteWithChildren,
  AccountHistoryRoute: AccountHistoryRoute,
  AccountLoyaltyRoute: AccountLoyaltyRoute,
  AccountNotificationsRoute: AccountNotificationsRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountVouchersRoute: AccountVouchersRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminAppointmentsRouteChildren {
  AdminAppointmentsIdRoute: typeof AdminAppointmentsIdRoute
  AdminAppointmentsIndexRoute: typeof AdminAppointmentsIndexRoute
}

const AdminAppointmentsRouteChildren: AdminAppointmentsRouteChildren = {
  AdminAppointmentsIdRoute: AdminAppointmentsIdRoute,
  AdminAppointmentsIndexRoute: AdminAppointmentsIndexRoute,
}

const AdminAppointmentsRouteWithChildren =
  AdminAppointmentsRoute._addFileChildren(AdminAppointmentsRouteChildren)

interface AdminCustomersRouteChildren {
  AdminCustomersIdRoute: typeof AdminCustomersIdRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
}

const AdminCustomersRouteChildren: AdminCustomersRouteChildren = {
  AdminCustomersIdRoute: AdminCustomersIdRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
}

const AdminCustomersRouteWithChildren = AdminCustomersRoute._addFileChildren(
  AdminCustomersRouteChildren,
)

interface AdminDoctorsRouteChildren {
  AdminDoctorsIdRoute: typeof AdminDoctorsIdRoute
  AdminDoctorsIndexRoute: typeof AdminDoctorsIndexRoute
}

const AdminDoctorsRouteChildren: AdminDoctorsRouteChildren = {
  AdminDoctorsIdRoute: AdminDoctorsIdRoute,
  AdminDoctorsIndexRoute: AdminDoctorsIndexRoute,
}

const AdminDoctorsRouteWithChildren = AdminDoctorsRoute._addFileChildren(
  AdminDoctorsRouteChildren,
)

interface AdminServicesRouteChildren {
  AdminServicesIdRoute: typeof AdminServicesIdRoute
}

const AdminServicesRouteChildren: AdminServicesRouteChildren = {
  AdminServicesIdRoute: AdminServicesIdRoute,
}

const AdminServicesRouteWithChildren = AdminServicesRoute._addFileChildren(
  AdminServicesRouteChildren,
)

interface AdminRouteChildren {
  AdminAppointmentsRoute: typeof AdminAppointmentsRouteWithChildren
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminBlogCategoriesRoute: typeof AdminBlogCategoriesRoute
  AdminBlogsRoute: typeof AdminBlogsRoute
  AdminCustomersRoute: typeof AdminCustomersRouteWithChildren
  AdminDoctorsRoute: typeof AdminDoctorsRouteWithChildren
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminServiceCategoriesRoute: typeof AdminServiceCategoriesRoute
  AdminServicesRoute: typeof AdminServicesRouteWithChildren
  AdminStaffRoute: typeof AdminStaffRoute
  AdminVoucherManagementRoute: typeof AdminVoucherManagementRoute
  AdminVouchersRoute: typeof AdminVouchersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAppointmentsRoute: AdminAppointmentsRouteWithChildren,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminBlogCategoriesRoute: AdminBlogCategoriesRoute,
  AdminBlogsRoute: AdminBlogsRoute,
  AdminCustomersRoute: AdminCustomersRouteWithChildren,
  AdminDoctorsRoute: AdminDoctorsRouteWithChildren,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminServiceCategoriesRoute: AdminServiceCategoriesRoute,
  AdminServicesRoute: AdminServicesRouteWithChildren,
  AdminStaffRoute: AdminStaffRoute,
  AdminVoucherManagementRoute: AdminVoucherManagementRoute,
  AdminVouchersRoute: AdminVouchersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogsRouteChildren {
  BlogsSlugRoute: typeof BlogsSlugRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
}

const BlogsRouteChildren: BlogsRouteChildren = {
  BlogsSlugRoute: BlogsSlugRoute,
  BlogsIndexRoute: BlogsIndexRoute,
}

const BlogsRouteWithChildren = BlogsRoute._addFileChildren(BlogsRouteChildren)

interface BookingRouteChildren {
  BookingSuccessRoute: typeof BookingSuccessRoute
}

const BookingRouteChildren: BookingRouteChildren = {
  BookingSuccessRoute: BookingSuccessRoute,
}

const BookingRouteWithChildren =
  BookingRoute._addFileChildren(BookingRouteChildren)

interface DoctorAppointmentsRouteChildren {
  DoctorAppointmentsIdRoute: typeof DoctorAppointmentsIdRoute
  DoctorAppointmentsIndexRoute: typeof DoctorAppointmentsIndexRoute
}

const DoctorAppointmentsRouteChildren: DoctorAppointmentsRouteChildren = {
  DoctorAppointmentsIdRoute: DoctorAppointmentsIdRoute,
  DoctorAppointmentsIndexRoute: DoctorAppointmentsIndexRoute,
}

const DoctorAppointmentsRouteWithChildren =
  DoctorAppointmentsRoute._addFileChildren(DoctorAppointmentsRouteChildren)

interface DoctorRouteChildren {
  DoctorAppointmentsRoute: typeof DoctorAppointmentsRouteWithChildren
  DoctorNotificationsRoute: typeof DoctorNotificationsRoute
  DoctorReviewsRoute: typeof DoctorReviewsRoute
  DoctorScheduleRoute: typeof DoctorScheduleRoute
  DoctorTodayRoute: typeof DoctorTodayRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
}

const DoctorRouteChildren: DoctorRouteChildren = {
  DoctorAppointmentsRoute: DoctorAppointmentsRouteWithChildren,
  DoctorNotificationsRoute: DoctorNotificationsRoute,
  DoctorReviewsRoute: DoctorReviewsRoute,
  DoctorScheduleRoute: DoctorScheduleRoute,
  DoctorTodayRoute: DoctorTodayRoute,
  DoctorIndexRoute: DoctorIndexRoute,
}

const DoctorRouteWithChildren =
  DoctorRoute._addFileChildren(DoctorRouteChildren)

interface DoctorsRouteChildren {
  DoctorsSlugRoute: typeof DoctorsSlugRoute
}

const DoctorsRouteChildren: DoctorsRouteChildren = {
  DoctorsSlugRoute: DoctorsSlugRoute,
}

const DoctorsRouteWithChildren =
  DoctorsRoute._addFileChildren(DoctorsRouteChildren)

interface ReceptionistAppointmentsRouteChildren {
  ReceptionistAppointmentsIdRoute: typeof ReceptionistAppointmentsIdRoute
  ReceptionistAppointmentsIndexRoute: typeof ReceptionistAppointmentsIndexRoute
}

const ReceptionistAppointmentsRouteChildren: ReceptionistAppointmentsRouteChildren =
  {
    ReceptionistAppointmentsIdRoute: ReceptionistAppointmentsIdRoute,
    ReceptionistAppointmentsIndexRoute: ReceptionistAppointmentsIndexRoute,
  }

const ReceptionistAppointmentsRouteWithChildren =
  ReceptionistAppointmentsRoute._addFileChildren(
    ReceptionistAppointmentsRouteChildren,
  )

interface ReceptionistRouteChildren {
  ReceptionistAppointmentsRoute: typeof ReceptionistAppointmentsRouteWithChildren
  ReceptionistCustomersRoute: typeof ReceptionistCustomersRoute
  ReceptionistNotificationsRoute: typeof ReceptionistNotificationsRoute
  ReceptionistTodayRoute: typeof ReceptionistTodayRoute
  ReceptionistIndexRoute: typeof ReceptionistIndexRoute
}

const ReceptionistRouteChildren: ReceptionistRouteChildren = {
  ReceptionistAppointmentsRoute: ReceptionistAppointmentsRouteWithChildren,
  ReceptionistCustomersRoute: ReceptionistCustomersRoute,
  ReceptionistNotificationsRoute: ReceptionistNotificationsRoute,
  ReceptionistTodayRoute: ReceptionistTodayRoute,
  ReceptionistIndexRoute: ReceptionistIndexRoute,
}

const ReceptionistRouteWithChildren = ReceptionistRoute._addFileChildren(
  ReceptionistRouteChildren,
)

interface ServicesCategorySlugRouteChildren {
  ServicesCategorySlugServiceSlugRoute: typeof ServicesCategorySlugServiceSlugRoute
  ServicesCategorySlugIndexRoute: typeof ServicesCategorySlugIndexRoute
}

const ServicesCategorySlugRouteChildren: ServicesCategorySlugRouteChildren = {
  ServicesCategorySlugServiceSlugRoute: ServicesCategorySlugServiceSlugRoute,
  ServicesCategorySlugIndexRoute: ServicesCategorySlugIndexRoute,
}

const ServicesCategorySlugRouteWithChildren =
  ServicesCategorySlugRoute._addFileChildren(ServicesCategorySlugRouteChildren)

interface ServicesRouteChildren {
  ServicesCategorySlugRoute: typeof ServicesCategorySlugRouteWithChildren
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesCategorySlugRoute: ServicesCategorySlugRouteWithChildren,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AppointmentLookupRoute: AppointmentLookupRoute,
  BlogsRoute: BlogsRouteWithChildren,
  BookingRoute: BookingRouteWithChildren,
  DoctorRoute: DoctorRouteWithChildren,
  DoctorsRoute: DoctorsRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ReceptionistRoute: ReceptionistRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SetupPasswordRoute: SetupPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
